//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace GMapGeocoder.Generated {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class kml {
        
        private Response responseField;
        
        /// <remarks/>
        public Response Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class Response {
        
        private string nameField;
        
        private Status statusField;
        
        private Placemark[] placemarkField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Placemark")]
        public Placemark[] Placemark {
            get {
                return this.placemarkField;
            }
            set {
                this.placemarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class Status {
        
        private int codeField;
        
        private string requestField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class Placemark {
        
        private string addressField;
        
        private AddressDetails addressDetailsField;
        
        private Point pointField;
        
        private string idField;
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public AddressDetails AddressDetails {
            get {
                return this.addressDetailsField;
            }
            set {
                this.addressDetailsField = value;
            }
        }
        
        /// <remarks/>
        public Point Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class AddressDetails {
        
        private Country countryField;
        
        private int accuracyField;
        
        /// <remarks/>
        public Country Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class Point {
        
        private string coordinatesField;
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class Country {
        
        private string countryNameCodeField;
        
        private AdministrativeArea administrativeAreaField;
        
        /// <remarks/>
        public string CountryNameCode {
            get {
                return this.countryNameCodeField;
            }
            set {
                this.countryNameCodeField = value;
            }
        }
        
        /// <remarks/>
        public AdministrativeArea AdministrativeArea {
            get {
                return this.administrativeAreaField;
            }
            set {
                this.administrativeAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class AdministrativeArea {
        
        private string administrativeAreaNameField;
        
        private SubAdministrativeArea subAdministrativeAreaField;
        
        private Locality localityField;
        
        /// <remarks/>
        public string AdministrativeAreaName {
            get {
                return this.administrativeAreaNameField;
            }
            set {
                this.administrativeAreaNameField = value;
            }
        }
        
        /// <remarks/>
        public SubAdministrativeArea SubAdministrativeArea {
            get {
                return this.subAdministrativeAreaField;
            }
            set {
                this.subAdministrativeAreaField = value;
            }
        }
        
        /// <remarks/>
        public Locality Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class SubAdministrativeArea {
        
        private string subAdministrativeAreaNameField;
        
        private Locality localityField;
        
        /// <remarks/>
        public string SubAdministrativeAreaName {
            get {
                return this.subAdministrativeAreaNameField;
            }
            set {
                this.subAdministrativeAreaNameField = value;
            }
        }
        
        /// <remarks/>
        public Locality Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class Locality {
        
        private string localityNameField;
        
        private Thoroughfare thoroughfareField;
        
        private PostalCode postalCodeField;
        
        /// <remarks/>
        public string LocalityName {
            get {
                return this.localityNameField;
            }
            set {
                this.localityNameField = value;
            }
        }
        
        /// <remarks/>
        public Thoroughfare Thoroughfare {
            get {
                return this.thoroughfareField;
            }
            set {
                this.thoroughfareField = value;
            }
        }
        
        /// <remarks/>
        public PostalCode PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class Thoroughfare {
        
        private string thoroughfareNameField;
        
        /// <remarks/>
        public string ThoroughfareName {
            get {
                return this.thoroughfareNameField;
            }
            set {
                this.thoroughfareNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public partial class PostalCode {
        
        private string postalCodeNumberField;
        
        /// <remarks/>
        public string PostalCodeNumber {
            get {
                return this.postalCodeNumberField;
            }
            set {
                this.postalCodeNumberField = value;
            }
        }
    }
}
